format = """
$battery\
[](#29089e)\
$os\
$username\
[](bg:#4b1df0 fg:#29089e)\
$directory\
[](fg:#4b1df0 bg:#704fe8)\
$git_branch\
$git_status\
[](fg:#704fe8 bg:#8d72ed)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$javascript\
$julia\
$nodejs\
$nim\
$python\
$ruby\
$rust\
$scala\
[](fg:#8d72ed bg:#8d72ed)\
$docker_context\
[](fg:#8d72ed bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[[battery.display]]
threshold = 10
style = "red"
discharging_symbol = ' '
charging_symbol =  '(red)•'

[[battery.display]]
threshold = 30
style = "yellow"
discharging_symbol = '[󰣇 ](#1793d1)'
charging_symbol =  '(yellow)•'

[[battery.display]]
threshold = 110
style = "#06732a"
discharging_symbol = '[󰣇 ](#1793d1)'
charging_symbol = '[󰣇 ](#1793d1)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#29089e"
style_root = "bg:#29089e"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#29089e"
disabled = true # Disabled by default

[directory]
style = "bg:#4b1df0"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = "󰋜"
"Projects" = "󰅩"
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#704fe8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#704fe8"
format = '[$all_status$ahead_behind ]($style)'
conflicted = ''
ahead = '⇡ '
behind = '⇣ '
diverged = ' '
up_to_date = ''
untracked = ' '
stashed = '󰏗 '
modified = ' '
staged = ' '
renamed = ' '
deleted = ' '

[golang]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "󰌠"
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#8d72ed"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'
